// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ibygfftdpbqjcayxzaax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlieWdmZnRkcGJxamNheXh6YWF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3NDIwODcsImV4cCI6MjA2ODMxODA4N30.-G55DmZ5Sj_O2ChT7yfxqLBZsMC4BAOvh2N1My7xRHQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});